### ISSUE TITLE
Add tests to encourage/guide collaboration?

### ISSUE THREAD

**Issue by jwsloan** [dry-rb/dry-web-blog#6]
@timriley 

I know this is meant to be an example of how to build with `dry-*` correctly, and I'm wondering if you'd be interested in having folks such as myself help, even if we're brand new (which I am).

If so, would you be willing to write up tests for each of your TODO items, and maybe push them to a separate branch? Then we could use those to drive attempts at implementing solutions. I'm sure the first shots would not be correct, but you could provide feedback until the solution was correct. 

This would provide ample opportunity for teaching, which would then be documented for posterity, and maybe this example would even have a better shot at getting completely fleshed out.

Thoughts?

**Comment by timriley** [comment]
Hi @jwsloan — I appreciate you reaching out! I do recognise progress on this has been a little slow lately, but I'm getting back into things now. I have to be honest and say that the only way I'm going to be able to do this, realistically, is build both specs/features together, and engage in any discussion that happens to occur along the way.

I do hope to get this to a good basic level of functionality and from that point (or any point along the way, really), anyone in the community is welcome to fork and extend things to their own liking :)
